<?php

namespace Database\Seeders;

use App\Models\Respondent;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;

class RespondentSeeder extends AbstractSeeder
{
    protected $modelClass = Respondent::class;

    protected function data(): array
    {
        return [

            // January            
            [
                'village_id' => 53073,
                'occupation_id' => 3,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Pelayanan disini sangat bagus',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '03/01/2023 00:00:00'),
            ],
            [
                'village_id' => 53076,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 6,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Tetap pertahankan pelayanan disini',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '01/01/2023 00:00:00'),
            ],
            [
                'village_id' => 3696,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus pelayanannya',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '04/01/2023 00:00:00'),
            ],
            [
                'village_id' => 27284,
                'occupation_id' => 3,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 3,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayan ramah-ramah',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '05/01/2023 00:00:00'),
            ],
            [
                'village_id' => 27360,
                'occupation_id' => 4,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 9,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Akan lebih baik jika dipertahankan',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '06/01/2023 00:00:00'),
            ],
            [
                'village_id' => 27318,
                'occupation_id' => 5,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 11,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Mantap',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '07/01/2023 00:00:00'),
            ],
            [
                'village_id' => 74,
                'occupation_id' => 5,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 2,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Good',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '08/01/2023 00:00:00'),
            ],
            [
                'village_id' => 32,
                'occupation_id' => 1,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 9,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Nice',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '09/01/2023 00:00:00'),
            ],
            [
                'village_id' => 74839,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayanan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '10/01/2023 00:00:00'),
            ],
            [
                'village_id' => 75971,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '11/01/2023 00:00:00'),
            ],
            [
                'village_id' => 82042,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayanan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '12/01/2023 00:00:00'),
            ],
            [
                'village_id' => 235,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '13/01/2023 00:00:00'),
            ],
            [
                'village_id' => 63749,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '14/01/2023 00:00:00'),
            ],
            [
                'village_id' => 3423,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayanan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '14/01/2023 00:00:00'),
            ],
            [
                'village_id' => 23,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '15/01/2023 00:00:00'),
            ],


            // February 
            [
                'village_id' => 3432,
                'occupation_id' => 3,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Pelayanan disini sangat bagus',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '03/02/2023 00:00:00'),
            ],
            [
                'village_id' => 5673,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 6,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Tetap pertahankan pelayanan disini',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '01/02/2023 00:00:00'),
            ],
            [
                'village_id' => 76854,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus pelayanannya',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '04/02/2023 00:00:00'),
            ],
            [
                'village_id' => 3453,
                'occupation_id' => 3,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 3,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayan ramah-ramah',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '05/02/2023 00:00:00'),
            ],
            [
                'village_id' => 4567,
                'occupation_id' => 4,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 9,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Akan lebih baik jika dipertahankan',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '06/02/2023 00:00:00'),
            ],
            [
                'village_id' => 3453,
                'occupation_id' => 5,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 11,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Mantap',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '07/02/2023 00:00:00'),
            ],
            [
                'village_id' => 2344,
                'occupation_id' => 5,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 2,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Good',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '08/02/2023 00:00:00'),
            ],
            [
                'village_id' => 4566,
                'occupation_id' => 1,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 9,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Nice',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '09/02/2023 00:00:00'),
            ],
            [
                'village_id' => 34533,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayanan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '10/02/2023 00:00:00'),
            ],
            [
                'village_id' => 457,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '11/02/2023 00:00:00'),
            ],
            [
                'village_id' => 45,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayanan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '12/02/2023 00:00:00'),
            ],
            [
                'village_id' => 685,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '13/02/2023 00:00:00'),
            ],


            // March
            [
                'village_id' => 345,
                'occupation_id' => 1,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Pelayanan disini sangat bagus',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '03/03/2023 00:00:00'),
            ],
            [
                'village_id' => 4545,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 6,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Tetap pertahankan pelayanan disini',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '01/03/2023 00:00:00'),
            ],
            [
                'village_id' => 666,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus pelayanannya',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '04/03/2023 00:00:00'),
            ],
            [
                'village_id' => 33,
                'occupation_id' => 3,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 3,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayan ramah-ramah',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '05/03/2023 00:00:00'),
            ],
            [
                'village_id' => 5637,
                'occupation_id' => 4,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 9,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Akan lebih baik jika dipertahankan',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '06/03/2023 00:00:00'),
            ],
            [
                'village_id' => 36345,
                'occupation_id' => 5,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 11,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Mantap',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '07/03/2023 00:00:00'),
            ],
            [
                'village_id' => 46736,
                'occupation_id' => 5,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 2,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Good',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '08/03/2023 00:00:00'),
            ],
            [
                'village_id' => 57856,
                'occupation_id' => 1,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 9,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Nice',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '09/03/2023 00:00:00'),
            ],
            [
                'village_id' => 23432,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 1,
                'service_id' => 1,
                'age_option_id' => 2,
                'gender' => 'Perempuan',
                'comment' => 'Pelayanan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '10/03/2023 00:00:00'),
            ],
            [
                'village_id' => 4444,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '11/03/2023 00:00:00'),
            ],
            [
                'village_id' => 4563,
                'occupation_id' => 2,
                'tenant_id' => 1,
                'division_id' => 2,
                'service_id' => 7,
                'age_option_id' => 2,
                'gender' => 'Laki-laki',
                'comment' => 'Bagus dan baik',
                'submitted_at' => Carbon::createFromFormat('d/m/Y H:i:s', '22/04/2023 00:00:00'),
            ],
        ];
    }
}